#!/bin/bash

set -e

_url="https://api2.pushdeer.com/message/push"
_key="$PUSHDEER_KEY"
_type="text"
_desp=""
_text=""
_pos=0

while getopts ":itmd:" opt; do
    case $opt in
        i) _type="image";;
        t) _type="text";;
        m) _type="markdown";;
        d) _desp=$OPTARG;;
    esac
    _pos=$OPTIND
done

_text=${BASH_ARGV[0]}

if [[ $_text == "-" ]]; then
    _text=$(cat <&0)
fi

if [ $_type == "markdown" ]; then
	resp=$(curl -X POST -F pushkey=$_key -F text="$_text" \
	-F type=$_type -F desp="$_desp" -fsSL $_url);
else
	resp=$(curl -X POST -F pushkey=$_key -F text="$_text" \
	-F type=$_type -fsSL $_url);
fi

exit $(echo $resp | grep -io '"code":[0-9]\+' | grep -o '[0-9]\+')